### ISSUE TITLE
無駄なベンダー接頭辞の削除

### ISSUE THREAD

**Issue by myakura** [sottar/filter-generator#1]
CSS Filterですが、[必要なベンダー接頭辞は`-webkit-filter`のみ](http://caniuse.com/#feat=css-filters)で、[現状のフィルタ用Mixin](https://github.com/sottar/filter-generator/blob/df257f2/src/sass/_instaEffects.scss#L22)ではかなり無駄なコードが出力されてしまいます。

ベンダー接頭辞は書かず、Autoprefixerなどで自動的に付加するようにするのはいかがでしょうか。

**Comment by sottar** [comment]
@myakura 
ご指摘いただきありがとうございます。

-webkit-filterのみ必要だったんですね。調査不足でした。
Autoprefixer、初めて知りました。ありがとうございます。
修正いたします。

**Comment by sottar** [comment]
@myakura 
ありがとうございました。
修正いたしました。
